// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN45_DzgKvl56r1F129CVlVdeD8gA4aWU',
    appId: '1:129790191006:web:ade5cc3cd2c2bdc29c628f',
    messagingSenderId: '129790191006',
    projectId: 'lawyeronline-a8424',
    authDomain: 'lawyeronline-a8424.firebaseapp.com',
    storageBucket: 'lawyeronline-a8424.firebasestorage.app',
    measurementId: 'G-GZ0KMKECVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN9jMqDw8rnrsYxQlCLX-6_Q8Y6SMONAU',
    appId: '1:129790191006:android:bbbf0c43a42eeb3d9c628f',
    messagingSenderId: '129790191006',
    projectId: 'lawyeronline-a8424',
    storageBucket: 'lawyeronline-a8424.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRKhSr43ChBLxg1u9r4OxAcaNgH_j4WnQ',
    appId: '1:129790191006:ios:19c92caf7258ef1f9c628f',
    messagingSenderId: '129790191006',
    projectId: 'lawyeronline-a8424',
    storageBucket: 'lawyeronline-a8424.firebasestorage.app',
    iosBundleId: 'td.webuild.lawyer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRKhSr43ChBLxg1u9r4OxAcaNgH_j4WnQ',
    appId: '1:129790191006:ios:e72e1a0e1a27b0f89c628f',
    messagingSenderId: '129790191006',
    projectId: 'lawyeronline-a8424',
    storageBucket: 'lawyeronline-a8424.firebasestorage.app',
    iosBundleId: 'com.example.videoCall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN45_DzgKvl56r1F129CVlVdeD8gA4aWU',
    appId: '1:129790191006:web:4024477e6c41631f9c628f',
    messagingSenderId: '129790191006',
    projectId: 'lawyeronline-a8424',
    authDomain: 'lawyeronline-a8424.firebaseapp.com',
    storageBucket: 'lawyeronline-a8424.firebasestorage.app',
    measurementId: 'G-B43LHYEE63',
  );
}
